const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
    SESSION_ID: process.env.SESSION_ID || " eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicVBSZ3E4MGhla0Q0bWVxTS9aUTFTWkI3UmJYVzhLY29WcnNWK3l1WWNWMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic3IzMHFDZ2lHQ09aS00raHY4ZnhSWHhpaWJ2ZE9jV2h4RkM5WS9zQlFuST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLSmo4am9iVmFoQ2JOa2RjQzg4MHVoZDdNR08xZEVIbkFhY0F3alNrWm1JPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2MzVlbE5yQUFvME1IODc5am9aMG9rK1JQdldBRFd3cll5WHRnNXFNODJFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNEbmZvdU02TVlBRFJMQXZqT2k1SGNYcXBXeWE3ODVWSHJCMUo3QjVWVU09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJLTWFBZnpUNExIV0JEVERXZkR6MkFlOTBLTWJmSncvSWRJbEpYQ0JYams9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ09mb001bTVKM0svUitabWNWeERBRWJTU0UyVTV0VFJuLzl3Ri9zbnlsdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiN01Oc1lnQTBIYW5YV0ljWUQ4Q2FZYmVRMVZYaCt0cVlJWnorS0ZCMEd6TT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilk1ZGdvSitrQnZodHdkRGY4Wm9SMWpaVVNzTFZrdHpGT0h0NHlYNWFtSGNFSk9kSDU3OEN3ZEZaVXdBa1lwYU8wei8vL0ZMYUpOSlhZWmQ3bE0rWkRBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTIsImFkdlNlY3JldEtleSI6ImtkZTIvcnlpYUNZQlRVNG44OVBwancvTXVDc004VlIxT0JnRmR3RldSR0k9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IjZERmVOVG4xUnhLN1R4UXVTb3I4Q1EiLCJwaG9uZUlkIjoiMjNhYThjZTktYzllZi00NGNmLThjMjItZjllMDhjODc1YjFkIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1VQWx5Z1JCbE9mN0Q0MjdOZzU5M3lHeG5HQT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIraWxpVU4vS0N4MUxSenFvWFhLYklVU0wrNkk9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiTjFHTEFDVEEiLCJtZSI6eyJpZCI6IjI1NTc0NjQyODgzNTo2OEBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLhtL/htLXhtpzhtLThtKzhtL/htLAo8J2RrPCdko7wnZKG8J2Sk/CdkorwnZKV8J2SlvCdkpQp4bac4bWe4bSu4bSx4bS/In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNLNzFxSWNHRUlYL2xMMEdHQXdnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJMUDJoUXZ5cm5SekRFME5GVEtNOWZkMnNJTENpUU5TY3BiRE5FZnZobFZZPSIsImFjY291bnRTaWduYXR1cmUiOiJpSEs3RkpUa1VmRlBrWkU2UWJKWGVzVWlYbnFnZXpCZE80N2N6OGF5ZllRVDlsWEdBaXNHNHA2MUJOM05scVE1c0ZML0tDV3o4S2d0Z2ZkWFd2QlZCdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiSnEwRzVkSk1sR0pRVkRSRjNYVGlDTDNsc01jZGFDdWx6MHZkbi9QaDJsc1Izb1VjdXlrKzU2RmZ1bFQrd1F2NGc4dmFWUkYwK05lQlRubGJCQ2JWQUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTU3NDY0Mjg4MzU6NjhAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCU3o5b1VMOHE1MGN3eE5EUlV5alBYM2RyQ0N3b2tEVW5LV3d6Ukg3NFpWVyJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczODg4Mjk2Mn0=  ",
    CAPTION: process.env.CAPTION || "code by yessertech ",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    AUTO_REPLY_STATUS: process.env.AUTO_REPLY_STATUS || "true",
    READ_MESSAGE: process.env.READ_MESSAGE || "true", // Added auto-read configuration
    MODE: process.env.MODE || "public",
    AUTO_VOICE: process.env.AUTO_VOICE || "false",
    AUTO_STICKER: process.env.AUTO_STICKER || "false",
    AUTO_REPLY: process.env.AUTO_REPLY || "false",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/3kdkf6.jpg",
    ALIVE_MSG: process.env.ALIVE_MSG || "hi i am richard md",
    ANTI_LINK: process.env.ANTI_LINK || "true",
    ANTI_BAD: process.env.ANTI_BAD || "true",
    PREFIX: process.env.PREFIX || ".",
    FAKE_RECORDING: process.env.FAKE_RECORDING || "false",
    FAKE_TYPING: process.env.FAKE_TYPING || "true",
    ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
    CURRENT_STATUS: process.env.CURRENT_STATUS || "true",
    AUTO_REACT: process.env.AUTO_REACT || "false",
    HEART_REACT: process.env.HEART_REACT || "true",
    OWNER_REACT: process.env.OWNER_REACT || "true",
    BOT_NAME: process.env.BOT_NAME || "emeritus tech",
    STATUS_REPLY: process.env.STATUS_REPLY || "`✅ your status seen 👀`",
    OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
